added test bash and ip arguments

diff --git a/snakemake/USEME b/snakemake/USEME
--- a/snakemake/USEME
+++ b/snakemake/USEME
@@ -1,4 +1,6 @@
 #!/bin/bash
+
+# Print the help page if asked
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]
 then
 echo "usage=\"USEME [-i FILE -o FILE] [-r FILE] [-c [True|False]] -- Program to filter out the bnign mutations inside a json.\"
@@ -13,6 +15,9 @@ Optional:
 "
 exit 0
 fi
+
+# Run application:
+## Get variables
 while getopts i:o:r:c: option
 do
 case "${option}"
@@ -24,6 +29,7 @@ c) CANCERONLY=$OPTARG;;
 esac
 done
 
+# Set default values
 if [ "$CANCERONLY" == "" ]
 then
 CANCERONLY=False
@@ -34,10 +40,13 @@ then
 REPORT=None
 fi
 
+# Gives error when the mandatory variables are not found
 if [ "$INPUT" == "" ] || [ "$OUTPUT" == "" ]
-then echo "Error: The -i and -o arguments has to be filled." | exit 1
+then echo "Error: The -i and -o arguments has to be filled." && exit 1
 fi
 
-python3 makeSnake.py $INPUT $OUTPUT $REPORT $CANCERONLY
-snakemake -F
-exit 0
+# Get IP address of the api container
+BDBIP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' benign_api)
+
+python3 makeSnake.py $INPUT $OUTPUT $REPORT $CANCERONLY $BDBIP
+snakemake --dag | dot -Tsvg > workflows/workflow_`date +%Y_%m_%d`_.svg && echo "Made a workflow. Check out the workflow directory!" && snakemake -F && exit 0
